In [309]:
import pandas as pd
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder , MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

import numpy as np

In [310]:
data_set=pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.train.csv")

In [311]:
data_set.head()

,Churn,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,No,4223-BKEOR,Female,0,No,Yes,21,Yes,No,DSL,...,No,Yes,No,No,Yes,One year,No,Mailed check,64.85,1336.8
1,No,6035-RIIOM,Female,0,No,No,54,Yes,Yes,Fiber optic,...,Yes,No,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),97.20,5129.45
2,Yes,3797-VTIDR,Male,0,Yes,No,1,No,No phone service,DSL,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,23.45,23.45
3,Yes,2568-BRGYX,Male,0,No,No,4,Yes,No,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.20,237.95
4,No,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,

In [312]:
Y=pd.DataFrame(data_set["Churn"])

In [313]:
columns=['Churn','gender','Partner','Dependents','PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod']

In [314]:
label_encoder=LabelEncoder()

In [315]:
#transformo la varibaili categoriche in numeri

In [316]:
for n in columns:
   data_set[n]=label_encoder.fit_transform(data_set[n])

In [317]:
data_set

,Churn,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,4223-BKEOR,0,0,0,1,21,1,0,0,...,0,2,0,0,2,1,0,3,64.85,1336.8
1,0,6035-RIIOM,0,0,0,0,54,1,2,1,...,2,0,0,2,2,2,1,0,97.20,5129.45
2,1,3797-VTIDR,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,1,2,23.45,23.45
3,1,2568-BRGYX,1,0,0,0,4,1,0,1,...,0,0,0,0,0,0,1,2,70.20,237.95
4,0,2775-SEFEE,1,0,0,1,0,1,2,0,...,2,0,2,0,0,2,1,0,61.90,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5629,1,0684-AOSIH,1,0,1,0,1,1,0,1,...,0,0,0,2,2,0,1,2,95.00,95
5630,0,5982-PSMKW,0,0,1,1,23,1,2,0,...,2,2,2,2,2,2,1,1,91.10,2198.3
5631,0,8044-BGWPI,1,0,1,1,12,1,0,2,...,1,1,1,1,1,0,1,2,21.15,306.05
5632,1,7450-NWRTR,1,1,0,0,12,1,2,1,...,0,2,0,2,2,0,1,2,99.45,1200.15
5633,0,4795-UXVCJ,1,0,0,0,26,1,0,2,...,1,1,1,1,1,1,0,1,19.80,457.3

In [318]:
Y=data_set['Churn']

In [319]:
data_set=data_set.drop(['Churn','customerID'],axis=1)

In [320]:
data_set.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [321]:
#transformo tutti gli elementi presenti nella colonna in interi

In [322]:
data_set['TotalCharges']=pd.to_numeric(data_set['TotalCharges'],errors='coerce')

In [323]:
#porto tutti i numeri presenti nella colonna totalcharges in un range tra 0-1

In [324]:
transform=[
    ['min_max_scaler',MinMaxScaler(),['TotalCharges']]
]

In [325]:
colum_transf_min_max=ColumnTransformer(transform,remainder='passthrough')

In [326]:
X_data=pd.DataFrame(colum_transf_min_max.fit_transform(data_set))

In [327]:
X_data.columns=['TotalCharges','gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges']

In [328]:
#inserisco i valori mancanti nella coonna TotalCharges

In [329]:


transform_imputer=[
    ['imputer',SimpleImputer(strategy="most_frequent"),['TotalCharges']]
]

In [330]:
colum_transf=ColumnTransformer(transform_imputer,remainder='passthrough')

In [331]:
X_data=pd.DataFrame(colum_transf.fit_transform(X_data))

In [332]:
X_data.columns=['TotalCharges','gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges']

In [333]:
X_data

,TotalCharges,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges
0,0.152089,0.0,0.0,0.0,1.0,21.0,1.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,1.0,0.0,3.0,64.85
1,0.589736,0.0,0.0,0.0,0.0,54.0,1.0,2.0,1.0,0.0,2.0,0.0,0.0,2.0,2.0,2.0,1.0,0.0,97.20
2,0.000537,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,23.45
3,0.025288,1.0,0.0,0.0,0.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,70.20
4,0.000162,1.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,2.0,2.0,0.0,2.0,0.0,0.0,2.0,1.0,0.0,61.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5629,0.008793,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,1.0,2.0,95.00
5630,0.251500,0.0,0.0,1.0,1.0,23.0,1.0,2.0,0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,91.10
5631,0.033147,1.0,0.0,1.0,1.0,12.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,2.0,21.15
5632,0.136320,1.0,1.0,0.0,0.0,12.0,1.0,2.0,1.0,0.0,0.0,2.0,0.0,2.0,2.0,0.0,1.0,2.0,99.45
5633,0.050600,1.0,0.0,0.0,0.0,26.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,19.80

In [343]:
X_train,X_test,Y_train,Y_test=train_test_split(X_data,Y)

In [344]:
rfc=RandomForestClassifier()

In [345]:
 rfc.fit(X_train,Y_train.values.ravel())

RandomForestClassifier()

In [349]:
predict=rf.predict(X_test)

In [350]:
accuracy=accuracy_score(predict,Y_test)

In [351]:
acc

0.950319375443577